messagingConfiguration:
  host: localhost
  connectionTimeout: 3600
  heartbeat: 3600
  queueName: crf_training_queue
  exchangeName: training_exchange
  exchangeRoutingKeys:
    - ner.crf
trainingConfiguration:
  dataPreparation:
    sentenceIndex: 0
    wordIndex: 1
    tagIndex: 3
  trainingDetails:
    outputFile: /external_mount/ner_model.pickle
    bucket: cbudhi-ml-models
    objectRef: ner/crf/model.pickle
    modelDict:
      algorithm: lbfgs
      c1: 0.1
      c2: 0.2
      max_iterations: 100
      all_possible_transitions: true
      verbose: true