version: 1
disable_existing_loggers: true
formatters:
  standard: 
    format: "[%(levelname)s] %(asctime)s %(name)s:%(lineno)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: ./logging/info.log
    maxBytes: 10485760
    backupCount: 5
    encoding: utf8
  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: standard
    filename: ./logging/error.log
    maxBytes: 10485760
    backupCount: 5
    encoding: utf8
root:
  level: NOTSET
  handlers: [console, info_file_handler, error_file_handler]
  propagate: yes
loggers: 
  training_module:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]
    propagate: no